In [1]:
#Q.1 Reverse a vector (first element becomes last)

import numpy as np
x=np.arange(10,25,5)
print(x)
x=np.flip(x,0) 
#x[::-1]
print(x)


[10 15 20]
[20 15 10]


In [6]:

#Q.2 Create a 3x3 matrix with values ranging from 0 to 8 */

import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Q.3 Create a 2d array with 1 on the border and 0 inside*/

import numpy as np
x = np.ones((4,4))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [10]:
import numpy as np
x = np.arange(0,15).reshape(5,3)
y = np.arange(1,7).reshape(3,2)
z=x.dot(y)
z



array([[ 13,  16],
       [ 40,  52],
       [ 67,  88],
       [ 94, 124],
       [121, 160]])

In [14]:
#extract integer part of random array
m = np.random.normal(0,5,10)
print(m)
print (m - m%1)
print (np.floor(m))
print (np.ceil(m)-1)

n = np.random.uniform(0,5,10)
print (n.astype(int))
print (np.trunc(n))

[-5.039292    4.51412269 -6.60272172 -9.26879748  1.97248944 -0.41042093
  5.60549393  2.27859006  0.08483588  1.55820517]
[ -6.   4.  -7. -10.   1.  -1.   5.   2.   0.   1.]
[ -6.   4.  -7. -10.   1.  -1.   5.   2.   0.   1.]
[ -6.   4.  -7. -10.   1.  -1.   5.   2.   0.   1.]
[4 4 4 4 2 4 2 4 4 2]
[4. 4. 4. 4. 2. 4. 2. 4. 4. 2.]


In [30]:
#Python program to check two random arrays are equal or not
x= np.random.rand(3,3)
y = np.random.rand(3,3)
np.array_equal(x, y)

False

In [31]:
#Python program to find the nearest value from a given value in an array
x= np.random.rand(3,3)
print(x)
v=1
n = x.flat[np.abs(x - v).argmin()]
print(n)

[[0.49183803 0.95275616 0.496778  ]
 [0.24889284 0.88451947 0.00605879]
 [0.27058384 0.63371887 0.28862525]]
0.9527561565778767


In [39]:
#Python program to get the n largest values of an array
#def largest_indices(ary, n):
#     """Returns the n largest indices from a numpy array."""
#     flat = ary.flatten()
#     indices = np.argpartition(flat, -n)[-n:]
#     indices = indices[np.argsort(-flat[indices])]
#     return np.unravel_index(indices, ary.shape)

# x= np.random.randint(3,3)
# print(x)
# print(largest_indices(x,3)
# )*/
n=3
arr = np.arange(9).reshape(3,3)
np.random.shuffle(arr)
arrf = arr.flat
ind = np.argsort(arrf)
arrf = arrf[ind]
arrf = arrf[::-1]
arrf[0:n]

array([8, 7, 6])

In [41]:
#How to find the closest value (to a given scalar) in an array?
x= np.random.randint(20, size=15)
print(x)
v=16
#v is the scalar
n = x.flat[np.abs(x - v).argmin()]
print(n)

[13  7 16  1 17 18  6  0 13  3 10 12 10  4 15]
16


In [48]:
#Python program to create random vector of size 15 and replace the maximum value by -1

j = np.random.randint(20, size=15)
max = j.max()
while (j.max() == max):
    x = j.argmax()
    j[x]=-1
print(j)

[ 2 11  3 10 17 -1 14  3 16  5  8  2 15 16  2]


In [66]:
#Consider a random vector with shape (100,2) representing coordinates, find point by point distance
import math
x = np.random.randint(5, 95, size=200).reshape(100,2)
z = np.zeros((100,100))

for i in range(0,100) :
    for j in range(0,100) :
        z[i,j] = np.trunc(math.sqrt(pow(x[i,0]-x[j,0],2)+pow(x[j,1]-x[j,1],2)))
        
print(z)

[[ 0. 34. 62. ... 41. 69. 48.]
 [34.  0. 28. ...  7. 35. 14.]
 [62. 28.  0. ... 21.  7. 14.]
 ...
 [41.  7. 21. ...  0. 28.  7.]
 [69. 35.  7. ... 28.  0. 21.]
 [48. 14. 14. ...  7. 21.  0.]]


In [68]:
#How to I sort an array by the nth column?

x = np.random.randint(1,11,(3,3))
y = x[:,2].argsort()
print(x)
print(x[y])

[[ 2  4 10]
 [ 5 10  7]
 [ 3  1  5]]
[[ 3  1  5]
 [ 5 10  7]
 [ 2  4 10]]


In [71]:
#Considering a four dimensions array, how to get sum over the last two axis at once

A=np.random.randint(0,10,(4,3,4,3))
# print(A)
sum=A.sum(axis=(2,3))
print(sum)


[[42 68 50]
 [36 57 67]
 [45 40 57]
 [61 66 77]]


In [77]:
#How to find the most frequent value in an array
a = np.random.randint(1,11,10)
counts = np.bincount(a)
print(a)
print (np.argmax(counts))

[ 6 10  8  2  4  4  7  2  3  8]
2
